### PR TITLE
second github action main.yml

### PR DESCRIPTION
**Pull request by dayofthetech**

### CODE REVIEW

**Comment by dayofthetech** [comment]
github actions passed after taking Jest out, is that because there is no Jest?
I see the `test` script but that runs  "craco test --transformIgnorePatterns 'node_modules/(?!axios)/' --detectOpenHandles --silent",

**Review by akosasante — APPROVED** [review]
This looks good to merge; only thing remaining is adding the `npm test` step for continuous integration 👍

**Comment by akosasante** [comment]
@dayofthetech since there's a few different branches and PRs open from you right now for the Github actions, maybe a good way forward is:

1.  merge this one to main
2.  close the other PRs/branches
3.  pull main to your local `main` branch
4.  create a new feature branch to complete the Github Action with the `npm test` command (making any needed change to `App.test.` to get the test passing
5.  open a PR for that new branch and get it reveiwed and merged
6.  move the Jira ticket for this task to the "Done" column :tada:

**Comment by akosasante** [comment]
> github actions passed after taking Jest out, is that because there is no Jest? I see the `test` script but that runs "craco test --transformIgnorePatterns 'node_modules/(?!axios)/' --detectOpenHandles --silent",

Jest should be in there via the create-react-app/craco library

What happens when you run the `npm run test` command locally?

If you look at the output of the failed test, you can see that the command ran totally fine: https://github.com/Code-the-Dream-School/dd-prac-team4-front/actions/runs/5843137989/job/15844981993

But the test that the command ran failed:

```
FAIL src/App.test.js (27.336 s)
  ● renders learn react link

    ReferenceError: Contact is not defined

      2[9](https://github.com/Code-the-Dream-School/dd-prac-team4-front/actions/runs/5843137989/job/15844981993#step:7:10) |     <>
      30 |       <h1>{message}</h1>
    > 31 |       <Contact />
         |        ^
      32 |     </>
      33 |   );
      34 | }

      at Component (src/App.js:31:8)
      at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:16305:18)
      at mountIndeterminateComponent (node_modules/react-dom/cjs/react-dom.development.js:20074:13)
      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:21587:16)
      at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:27426:14)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:26560:12)
      at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:26466:5)
      at renderRootSync (node_modules/react-dom/cjs/react-dom.development.js:26434:7)
      at recoverFromConcurrentError (node_modules/react-dom/cjs/react-dom.development.js:25850:20)
      at callback (node_modules/react-dom/cjs/react-dom.development.js:25750:22)
      at flushActQueue (node_modules/react/cjs/react.development.js:2667:24)
      at actImplementation (node_modules/react/cjs/react.development.js:2582:11)
      at node_modules/@testing-library/react/dist/act-compat.js:46:25
      at renderRoot (node_modules/@testing-library/react/dist/pure.js:161:25)
      at render (node_modules/@testing-library/react/dist/pure.js:247:[10](https://github.com/Code-the-Dream-School/dd-prac-team4-front/actions/runs/5843137989/job/15844981993#step:7:11))
      at Object.<anonymous> (src/App.test.js:5:9)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:[13](https://github.com/Code-the-Dream-School/dd-prac-team4-front/actions/runs/5843137989/job/15844981993#step:7:14))
      at runJest (node_modules/@jest/core/build/runJest.js:404:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:320:7)
      at runCLI (node_modules/@jest/core/build/cli/index.js:[17](https://github.com/Code-the-Dream-School/dd-prac-team4-front/actions/runs/5843137989/job/15844981993#step:7:18)3:3)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        [28](https://github.com/Code-the-Dream-School/dd-prac-team4-front/actions/runs/5843137989/job/15844981993#step:7:29).557 s
```

That test is defined here: https://github.com/Code-the-Dream-School/dd-prac-team4-front/blob/main/src/App.test.js

The test is complaining that the `<Contact/>` component is used in `App.js` but it's not actually imported in that file so Javascript does not know how to use it.

Then after fixing that, like my comment in one of the previous PRs, we need to also update the test itself since it is looking for the text "learn react" which used to work when this repo was first started; but now that we've updated the home page, will no longer pass since we're not rendering that text there anymore. Feel free to reach out to me with a time that works for you and I'll be happy to pair program with you on this 😄

**Pull request merged**
