### PR TITLE
github actions branch

### PR DESCRIPTION
**Pull request by dayofthetech**
working on ticket PS44 github actions - I decided to create a PR because when running current github actions an error message pointed at not having package-lock.json file in sync - This branch is directly off main so I would like to think is updated. 

I also rename Contact to SignIn element and remove it from showing in App.js

### CODE REVIEW

**Comment by dayofthetech** [comment]
github actions patch #3 still with error about package-lock.json not being sync. How can I confirm patch 3 points to my new branch `github actions` and files are in sycn?

**Comment by akosasante** [comment]
For this message: 

```
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
```

Hmm try doing a fully clean install. Delete `package-lock.json` and `node_modules` locally. Then run `npm install`.  Commit the changes for `package-lock.json` and push them to Github and see if the action is still failing.

**Comment by dayofthetech** [comment]
image

image

Follow steps

**Comment by akosasante** [comment]
@dayofthetech  Hey Alberto :wave:  Sorry my last comment I wrote unclearly, that's my mistake :disappointed:  I said "push them" but I only mean to push `package-lock.json`. 

It looks like we have `node_modules` in here now but not `package-lock.json`. We generally never want to add \`node\_modules\`  since it can be _huge._ For making sure Github Actions has the right set of dependencies we only need to do `git add package-lock.json` .

We can more or less follow the steps in this gist for getting that `node_modules` out of this branch's changes: https://gist.github.com/lmcneel/45594e550a3403d589bdcaad38138a83

1.  First, make sure `.gitignore` has a line in there to ignore `node_modules` (step 3 in that link)
2.  `git rm -r --cached node_modules` to get rid of node\_modules in git state
3.  `git commit -m "Removed node_modules folder"`
4.  `git add package-lock.json .gitignore` to add just the npm lockfile and the updated gitignore file to the staged changes
5.  `git push` to push to this branch

Sorry about that!

**Comment by dayofthetech** [comment]
No need to apologize Akos, I have drop the ball and then it just snowball into more issues that shouldn't occur because of all the training I have done with CTD. 
I'm the one that should apologize and again thank you so much for your feedback and efforts 🙏

**Review by dayofthetech — COMMENTED** [review]
The latest commit shows node-modules in the gitignore file

**Pull request closed without merging**
