### PR TITLE
ticket PS-55 album details

### PR DESCRIPTION
**Pull request by dayofthetech**
I have a few issues - first there are compiled problems with `CheckoutFrom.js` ( I will attach screenshoots)

ERROR in ./src/components/Purchase/CheckoutForm.js 6:0-108

Module not found: Error: Can't resolve '@stripe/react-stripe-js' in 'C:\Users\alber\react-folder\Practicum Project\dd-prac-team4-front\src\components\Purchase'

ERROR in ./src/components/Purchase/CheckoutPage.js 6:0-47

Module not found: Error: Can't resolve '@stripe/stripe-js' in 'C:\Users\alber\react-folder\Practicum Project\dd-prac-team4-front\src\components\Purchase'

ERROR in ./src/components/Purchase/CheckoutPage.js 7:0-51

Module not found: Error: Can't resolve '@stripe/react-stripe-js' in 'C:\Users\alber\react-folder\Practicum Project\dd-prac-team4-front\src\components\Purchase'

After I comment out `CheckoutForm.js` I'm able to work only on `AlbumDetails.js`  but it wont work - so I treid a barebone `App.js` code and it did work ( I did this to try and see if axios was working)

### CODE REVIEW

**Comment by dayofthetech** [comment]
If I only run the barebone `App.js` I do get record details

image

But I'm not sure how will it be added to `AlbumGrid.js` or to `Album.js` -> 
The fetching on `AlbumDetails.js` works but ideally I would want all that in `Album.js` right? - then maybe a useEffect when the album gets clicked??

**Comment by akosasante** [comment]
@dayofthetech do you see the following lines in your `package.json` file?  
 

```
    "@stripe/react-stripe-js": "^2.1.2",
    "@stripe/stripe-js": "^2.1.0",
```

If you do, you may just need to do an `npm install` so that those libraries are saved to your local node\_modules and everything should work. Let me know if not.

If not, you may be missing some recent merges from main; do a `git pull origin main` while you're on this branch (or in VS Code, in the Source Control panel, click the three dots menu and then select "Pull from..." and type in `origin/main`). 

Then do `npm install` and try to run the app again. Let me know if you run into any trouble

**Comment by akosasante** [comment]
For PS-55 we only need to be displaying more detailed infor about a specific album (since we currently already have a way to show a list of albums with your previous work on `<AlbumGrid>` and `<Album>` components.

In this ticket we want to be able to see more info about an album, and possibly in future tickets also be able to view reviews and ratings about the album. We originally envisioned a separate page; but it could also work as a modal on the AlbumGrid page so that you don't have to navigate to a whole other page like you mentioned. 

In either case, since we get to this component from the AlbumGrid, we should already have the album info fetched by `<AlbumList>`. Then this `<AlbumDetails>` component can have the album passed to it, so it doesn't need to do any of its own fetching necessarily. Often in React we want to do fetches higher up in the hierarchy and the pass information down the component tree.

So let's say the `AlbumDetails` component took an album as its props; that would look like:

```javascript
const AlbumDetails = ({album}) => {
// we can remove this useState and the below useEffect; we will receive the album from a parent component:

  // const [albums, setAlbums] = useState([]);

  // useEffect(() => {
  //   const fetchAlbums = async () => {
  //     try {
  //       const response = await axios.get('http://localhost:8000/api/v1/albums');
  //       setAlbums(response.data.albums); // Update to access the "albums" array
  //     } catch (error) {
  //       console.error('Error fetching albums:', error);
  //     }
  //   };
  //
  //   fetchAlbums();
  // }, []);


// If the component is mounted or is being unmounted and there's no album passed in yet, we don't want
// to throw an error, instead just have the component return null / empty react node. 
if (!album) return null;

// This component shows details about a single album, so we can remove the mapping over a list parts

  return (
    <div>
      <h1>Album Details</h1>
      <ul>
      {/*  {albums.map(album => (*/}
          <li key={album._id}>
            <h2>{album.albumName}</h2>
            <p>Artist: {album.artistName}</p>
            <p>Price: ${album.price.toFixed(2)}</p>
            <img src={album.image} alt={album.albumName} style={{ maxWidth: '200px' }} />
            {/* Additional album details can be displayed here */}
          </li>
        {/*))}*/}
      </ul>
    </div>
  );
};

export default AlbumDetails;
```

If you want to test out how this looks you can create a temporary route in `App.js` like what you did. And then I just copied the album information from the real page for one album and put that as a variable to pass in for now:

```javascript
const testAlbum = {
  "_id": "64d2ae2308a725b72bd5c0cf",
  "artistName": "Calvin Harris, Sam Smith",
  "albumName": "Desire (with Sam Smith)",
  "price": 91,
  "image": "https://i.scdn.co/image/ab67616d0000b27362aaea327f6977dae3c94cdf",
  "releaseDate": "2023-07-28T00:00:00.000Z",
  "spotifyUrl": "https://api.spotify.com/v1/albums/3XDtRvXV5DR1xZfvcneG2C",
  "averageRating": 0,
  "numOfReviews": 0,
  "__v": 0,
  "createdAt": "2023-08-08T21:05:39.693Z",
  "updatedAt": "2023-08-28T14:31:35.400Z",
  "id": "64d2ae2308a725b72bd5c0cf"
}

function App() {
  const { status } = useAuth();
  const isLoggedIn = status === AuthStatus.LoggedIn;
  return (
    <>
      <Navbar />
      <Routes>
        <Route
          path="/"
          element={isLoggedIn ? <Home /> : <Navigate to="/signIn" />}
        />
        <Route path="/register" element={<UserRegistration />} />
        <Route path="/signIn" element={<SignIn />} />
        <Route path="/home" element={<Home />} />
        <Route path="/checkout" element={<CheckoutPage />} />

        {/* Temporary route to test Ticket PS-55 */}
         <Route path="/album" element={<AlbumDetails album={testAlbum} />} />
      </Routes>
    </>
  );
}

export default App;
```

You'll need to remove this code before merging but it can be helpful to have a route to go to to easily see what your component renders while you're developing it.

---

Now as for your question about how to integrate this with the album marketplace page. It all depends on how you want it to look. From the last standup it sounded like you wanted to have this details show up as a modal on the same page instead of navigating away. And I think you mentioned a user clicking on the album image to trigger this (please correct me if I'm misremembering and putting words in your mouth, sorry!).

In that case, since the album art is rendered by the `<Album>` component, you would need to add an `onClick` handler in there: https://github.com/Code-the-Dream-School/dd-prac-team4-front/blob/0836f62ec2c1d4c5894d4d49ba69fffd9eedf749/src/components/Album.js#L9

```javascript
<img src={album.image} alt={album.albumName} className="album-image" onClick={openAlbumDetails} />
```

To make our modal, we can use the `<Dialog>` component from Material-UI: [https://mui.com/material-ui/react-dialog/#optional-sizes](https://mui.com/material-ui/react-dialog/#optional-sizes). In this case I opted to use one with the `maxWidth` to make the modal a bit bigger but you can play around with the values shown in that link. There's a few different ways we could choose to organize this code, but for now to keep it simple lets put it in the same component as our click handler, in the `<Album>` component; at the bottom of the component root element:

```javascript
return (
    <Grid item xs={12} sm={6} md={4}>
      <div className="album-item">
        <img src={album.image} alt={album.albumName} className="album-image" onClick={openAlbumDetails} />
        <p className="album-title">{album.albumName}</p>
        <p className="album-artist">{album.artistName}</p>
        <div className="button-container">
          <Button variant="contained" color="primary" className="buy-button">
            Buy
          </Button>
          <Button
            variant="contained"
            color="secondary"
            className="wishlist-button"
          >
            Wishlist
          </Button>
        </div>
      </div>

      <Dialog
        open={selectedAlbum?.id === album.id}
        onClose={handleCloseDialog}
        aria-labelledby="album-details-dialog-title"
        aria-describedby="album-details-dialog-description"
        maxWidth='lg'
      >
        <DialogContent>
            <AlbumDetails album={selectedAlbum} />
        </DialogContent>
      </Dialog>
    </Grid>
  );
```

*   we are telling the dialog modal to be open, if the `selectedAlbum` id is present and matches the `album.id` that was passed into this component
*   We will need to write a `handleCloseDialog` event handler to close the modal
*   We are rendering the `AlbumDetails` component here and passing in the `selectedAlbum` variable

Now we need to write the `openAlbumDetails` and `handleCloseDialog` handlers. We basically want to populate `selectedAlbum` with all the album details when the image is clicked. And then set it back to null when the modal is exited. Since this variable wiill be internal state to this component, we'll use `useState`:

```
  const [selectedAlbum, setSelectedAlbum] = React.useState(null);

  const openAlbumDetails = () => {
    setSelectedAlbum(album);
  }
  const handleCloseDialog = () => {
    setSelectedAlbum(null);
  }
```

Hope that gets you going!

**Comment by dayofthetech** [comment]
image

The dialog message pops up when click on the album image and disappear when click outside
details so far are **release date** and **average rating** 
not sure what other details to add

**Comment by akosasante** [comment]
>  not sure what other details to add

Nice! :tada:  I think that's good for now; you could add _**image**_ and the addtocheckout + wishlist buttons. Apart from that I can't think of anything for right now. In following tickets we'll try to include reviews in there, along with maybe a track preview or track listing.

**Review by akosasante — APPROVED** [review]
Looks great! You'll need to do a git pull from main and resolve any conflicts as I think a recent PR made some changes to the `Album.js` component. But after that you should be good to merge if you get the checkmark from Github Actions.

Let me know if you have any ideas/thoughts for additional content to put in the card.

**Pull request merged**
