### PR TITLE
Fixing conflict issues

### PR DESCRIPTION
**Pull request by JafariM**

### CODE REVIEW

**Review by akosasante — COMMENTED** [review]
Is this PR needed as a separate PR?

**Comment by JafariM** [comment]
I don't know what I do wrong about git and GitHub but every time I pull the main branch I got so many conflicts. The conflicts were in different files so I think I should create a new PR for that

**Comment by akosasante** [comment]
> I don't know what I do wrong about git and GitHub but every time I pull the main branch I got so many conflicts. The conflicts were in different files so I think I should create a new PR for that

Were you on a feature branch (a branch for a ticket) or on your local `main` branch when you did `git pull main` and got a bunch of conflicts? If it's a feature branch let me know which one and I can try and help resolve the conflicts on your behalf. If it's on the main branch we may need to set some time aside to chat in Slack or in a Slack Huddle to try and get it cleaned up :slightly\_smiling\_face:

**Comment by JafariM** [comment]
> > I don't know what I do wrong about git and GitHub but every time I pull the main branch I got so many conflicts. The conflicts were in different files so I think I should create a new PR for that
> 
> Were you on a feature branch (a branch for a ticket) or on your local `main` branch when you did `git pull main` and got a bunch of conflicts? If it's a feature branch let me know which one and I can try and help resolve the conflicts on your behalf. If it's on the main branch we may need to set some time aside to chat in Slack or in a Slack Huddle to try and get it cleaned up 🙂

It happened when I am on a feature branch

**Comment by akosasante** [comment]
I'm not sure if this is still needed or can be closed?

**Comment by JafariM** [comment]
> I'm not sure if this is still needed or can be closed?

No, it is no more needed, I will close that

**Pull request closed without merging**
